language: python

python:
  - 3.5

sudo: false

env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=py27-flake8
  - TOX_ENV=py35-flake8

matrix:
  fast_finish: true

install:
  - pip install "virtualenv<14.0.0" tox coveralls

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls
