#!/usr/bin/env bash


SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd );
source "$SCRIPT_DIR/common.sh";


if [ -d "$VENV_ROOT_PATH/bin" ]
then
    source "$VENV_ROOT_PATH/bin/activate";
else
    echo "\`api_mimic_build_venv\` has not been set up?";
    exit 1;
fi
